sudo: required
dist: trusty
addons:
  apt:
    update: true
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - 6.9.2
cache:
  directories:
    - node_modules
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
script:
  - npm test
  - cat ./test/coverage/lcov.info | ./node_modules/.bin/codecov

